// Shared universe - safe to import on client and server
export const SCAN_UNIVERSE: Array<{ ticker: string; name: string; sector: string }> = [
  { ticker: "IONQ", name: "IonQ Inc", sector: "Technology" },
  { ticker: "RGTI", name: "Rigetti Computing", sector: "Technology" },
  { ticker: "QBTS", name: "D-Wave Quantum", sector: "Technology" },
  { ticker: "SOUN", name: "SoundHound AI", sector: "Technology" },
  { ticker: "BBAI", name: "BigBear.ai", sector: "Technology" },
  { ticker: "KOPN", name: "Kopin Corporation", sector: "Technology" },
  { ticker: "MVST", name: "Microvast Holdings", sector: "Technology" },
  { ticker: "ACMR", name: "ACM Research", sector: "Healthcare" },
  { ticker: "ADMA", name: "ADMA Biologics", sector: "Healthcare" },
  { ticker: "CLOV", name: "Clover Health", sector: "Healthcare" },
  { ticker: "HIMS", name: "Hims & Hers Health", sector: "Healthcare" },
  { ticker: "PLUG", name: "Plug Power", sector: "Energy" },
  { ticker: "BLDP", name: "Ballard Power Systems", sector: "Energy" },
  { ticker: "BE", name: "Bloom Energy", sector: "Energy" },
  { ticker: "FCEL", name: "FuelCell Energy", sector: "Energy" },
  { ticker: "AFRM", name: "Affirm Holdings", sector: "Financials" },
  { ticker: "UPST", name: "Upstart Holdings", sector: "Financials" },
  { ticker: "SOFI", name: "SoFi Technologies", sector: "Financials" },
  { ticker: "HOOD", name: "Robinhood Markets", sector: "Financials" },
  { ticker: "DAVE", name: "Dave Inc", sector: "Financials" },
  { ticker: "RKLB", name: "Rocket Lab USA", sector: "Industrials" },
  { ticker: "ASTS", name: "AST SpaceMobile", sector: "Industrials" },
  { ticker: "LUNR", name: "Intuitive Machines", sector: "Industrials" },
  { ticker: "KTOS", name: "Kratos Defense", sector: "Industrials" },
  { ticker: "SMCI", name: "Super Micro Computer", sector: "Technology" },
  { ticker: "ALAB", name: "Astera Labs", sector: "Technology" },
  { ticker: "LSCC", name: "Lattice Semiconductor", sector: "Technology" },
  { ticker: "MSTR", name: "MicroStrategy", sector: "Technology" },
  { ticker: "CIFR", name: "Cipher Mining", sector: "Technology" },
  { ticker: "CLSK", name: "CleanSpark", sector: "Technology" },
  { ticker: "MARA", name: "Marathon Digital", sector: "Technology" },
  { ticker: "WULF", name: "TeraWulf", sector: "Technology" },
  { ticker: "XPOF", name: "Xponential Fitness", sector: "Consumer" },
  { ticker: "ATER", name: "Aterian Inc", sector: "Consumer" },
  { ticker: "MAXN", name: "Maxeon Solar", sector: "Energy" },
  { ticker: "BTBT", name: "Bit Digital", sector: "Technology" },
  { ticker: "TALK", name: "Talkspace", sector: "Healthcare" },
  { ticker: "GROV", name: "Grove Collaborative", sector: "Consumer" },
  { ticker: "BIRD", name: "Allbirds", sector: "Consumer" },
  { ticker: "CAMT", name: "Camtek Ltd", sector: "Technology" },
];
